# Basic configuration

- ec2_asg:
    name: "{{project_name}}-asg"
    load_balancers: [ '{{project_name}}-lb' ]
    availability_zones: [ 'us-east-1a', 'us-east-1c','us-east-1d','us-east-1e' ]
    launch_config_name: "{{project_name}}-lc"
    min_size: 1
    max_size: 1
    desired_capacity: 1
    region: "{{region}}"
    vpc_zone_identifier: [ '{{vpc.subnets[0].id}}', '{{vpc.subnets[1].id}}', '{{vpc.subnets[2].id}}', '{{vpc.subnets[3].id}}' ]
    tags:
      - environment: production
      - name: "{{project_name}}-asg"
        propagate_at_launch: no
